#!/usr/bin/env bash
# Redirection with nginx

sudo apt-get update
sudo apt-get -y install nginx

sudo echo "Hello World!" > /var/www/html/index.html

SERVER_CONFIG=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location / {
		try_files \$uri \$uri/ =404;
	}
	if (\$request_filename ~ redirect_me){
		rewrite ^ https://www.twitter.com/OluwninsolaAO permanent;
	}
}"

bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"
sudo /etc/init.d/nginx restart
