#!/usr/bin/env bash
# A custom 404 page that contains the string `Ceci n'est pas une page`.

sudo apt-get update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

SERVER_CONFIG=\
"server {
   listen 80 default_server;
   listen [::]:80 default_server;
   
   root /var/www/html;
   index index.html;
   location /redirect_me {
      return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
   }
   error_page 404 /404.html;
   location = /404.html{
      internal;
   }
}"

bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"
sudo /etc/init.d/nginx restart
