#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a
# compressed archive out of it.

# Dump all databases
mysqldump --all-databases -uroot -p"$1" > backup.sql

# Create archive
F_NAME=$(date +"%d-%m-%Y.tar.gz")
tar -czf "$F_NAME" backup.sql
