#!/usr/bin/env bash
# Nginx likes port 80 -- debugbing nginx not running on port 80
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
sudo /etc/init.d/nginx restart
sudo rm /var/run/nginx.pid
