#!/usr/bin/env bash
# A simple bash script that does the following:
# - Creates the file ``/var/run/myscript.pid``
#   containing its PID.
# - Displays ``To infinity and beyond`` indefinitely.
# - Displays ``I hate the kill command`` when receiving
#   a ``SIGTERM`` signal.
# - Displays ``Y U no love me?!`` when receiving a
#   ``SIGINT`` signal.
# - Deletes the file ``/var/run/myscript.pid`` and terminates
#   itself when receiving a ``SIGQUIT`` or ``SIGTERM`` signal.

FILENAME="/var/run/myscript.pid"
cleanup() {
	rm "$FILENAME"
	exit
}

pgrep -f "$0" > "$FILENAME"
while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command"; cleanup' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'cleanup' SIGQUIT
done
