#!/usr/bin/env bash
# A simple bash script that gives information
# about a file name ``school``.

STR="school"
DUMP_FILE="out_dump"
F_EXIST=0
F_EMPTY=0
F_IS_A_DIRECTORY=0

# if file exists:
file "$STR" > "$DUMP_FILE"
(( F_EXIST = $(< "$DUMP_FILE" grep -c "cannot open") ))
(( F_EMPTY = $(< "$DUMP_FILE" grep -c "empty") ))
(( F_IS_A_DIRECTORY = $(< "$DUMP_FILE" grep -c "directory") ))

if [ $F_EXIST -eq 0 ]
then
	echo "school file exists"
	if [ $F_EMPTY -eq 1 ]
	then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi
	if [ $F_IS_A_DIRECTORY -eq 0 ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
rm "$DUMP_FILE"
